name: Test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  testInsecure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run npm audit
        working-directory: insecure
        run: npm i --package-lock-only; npm audit
