name: Test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  testInsecure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run npm audit
        working-directory: insecure
        run: npm i --package-lock-only; npm audit
  testMashup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Syntax
        working-directory: mashup
        run: npm install eslint ; npm run lint index.js
  testUnittesting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Language thingy
        working-directory: unittesting
        run: npm install ; npm run test
