name: Test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  test insecure:
    runs-on: ubuntu-latest
    steps:
      - name: Run npm audit
        working-directory: ./insecure
        run: cd insecure ; npm i --package-lock-only; npm audit
